source_dir = "C:/Users/odhra/Downloads/"
book_dir = "C:/Users/odhra/Documents/Books/"
document_dir = "C:/Users/odhra/Documents/"
music_dir = "C:/Users/odhra/Music/"
pdf_dir = "C:/Users/odhra/Documents/PDFs/"
sql_dir = "C:/Users/odhra/Documents/SQL_Scripts/"
image_dir = "C:/Users/odhra/Pictures/"
video_dir = "C:/Users/odhra/Videos/"